title: hugopl devblog
description: hugopl writes about his pet projects and general software development
url: http://hugopl.github.io/
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
future: true
