name: hugopl devblog
description: hugopl writes about his pet projects and general software development
url: http://hugopl.github.io/
markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5
